name: chemsearch
channels:
  - conda-forge
  - defaults
  - rdkit
dependencies:
  - pip
  - python>=3.6
  - flask
  - flask-wtf
  - rdkit
  - pandas
  - oauth2client
  - openbabel
  - python-dotenv
  - google-api-python-client
  - google-auth
  - google-auth-httplib2
  - gunicorn
  - flask-bootstrap
  - matplotlib
  - Flask-Login
  - Flask-SQLAlchemy
  - rauth
  - Flask-Moment
  - beautifulsoup4
  - markdown
  - bleach
  - pyyaml
  - gevent
  - more-itertools
  - pip:
    - flask-shell-ipython
    - flask-migrate
