name: chemsearch
channels:
  - conda-forge
  - defaults
  - rdkit
dependencies:
  - pip
  - python=3
  - flask
  - flask-wtf
  - rdkit
  - jupyter
  - jupyterlab
  - pandas
  - oauth2client
  - openbabel
  - python-dotenv
  - jupyter_contrib_nbextensions
  - google-api-python-client
  - google-auth
  - google-auth-httplib2
  - gunicorn
  - flask-bootstrap
  - matplotlib
  - pip:
    - gspread
    - pyscaffold
    - Flask-Session

